Editing help URL and associated menu items.
metomi/rose pull request #2411
Opened 2020-09-27 23:59 UTC by jonnyhtw

Hi there

This is my go at updating the ROSE help GUI URL as per issue #2410 .

All the best!

Jonny

2020-09-28 09:04 UTC, wxtim commented
@jonnyhtw  - Don't worry about the test failures - these won't be related.

2020-09-28 09:07 UTC, wxtim commented on lib/python/rose/config_editor/window.py
> +        webbrowser.open('https://metomi.github.io/rose/doc/html/index.html', new=True, autoraise=True)
```suggestion
        webbrowser.open(
            'https://metomi.github.io/rose/doc/html/index.html',
            new=True,
            autoraise=True
        )
```

2020-09-28 09:08 UTC, wxtim approved these changes
Approve subject to fixing over-long line.

2020-09-28 20:26 UTC, jonnyhtw commented
> @jonnyhtw - Don't worry about the test failures - these won't be related.

OK thanks! I was gonna ask!... 😄

2020-09-30 10:55 UTC, oliver-sanders requested changes
Trying this out I'm getting traceback.

```
$ Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "~/rose/lib/python/rose/config_editor/main.py", line 2026, in <module>
    main()
  File "~/rose/lib/python/rose/config_editor/main.py", line 2022, in main
    no_warn=opts.no_warn)
  File "~/rose/lib/python/rose/config_editor/main.py", line 1882, in spawn_window
    no_warn=no_warn)
  File "~/rose/lib/python/rose/config_editor/main.py", line 285, in __init__
    self.generate_menubar()
  File "~/rose/lib/python/rose/config_editor/main.py", line 588, in generate_menubar
    widget.connect('activate', action)
AttributeError: 'NoneType' object has no attribute 'connect'
```

I think this is because the action has been renamed, but not in all places:

```console
$ git grep 'GUI Help'
demo/rose-config-edit/test/doc/test_suite:Help-> GUI Help
demo/rose-config-edit/test_suite:Help-> GUI Help
lib/python/rose/config_editor/__init__.py:TOP_MENU_HELP_GUI = "_GUI Help"
lib/python/rose/config_editor/main.py:            ('/TopMenuBar/Help/GUI Help', self.main_handle.help),
lib/python/rosie/browser/__init__.py:TOP_MENU_GUI_HELP = "_GUI Help"
lib/python/rosie/browser/main.py:                     ('/TopMenuBar/Help/GUI Help',
lib/python/rosie/browser/util.py:        <menuitem action="GUI Help"/>
lib/python/rosie/browser/util.py:                      ('GUI Help', gtk.STOCK_HELP,
```

How about renaming to "Documentation"?

2020-09-30 22:29 UTC, jonnyhtw commented
> Trying this out I'm getting traceback.
> 
> ```
> $ Traceback (most recent call last):
>   File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "~/rose/lib/python/rose/config_editor/main.py", line 2026, in <module>
>     main()
>   File "~/rose/lib/python/rose/config_editor/main.py", line 2022, in main
>     no_warn=opts.no_warn)
>   File "~/rose/lib/python/rose/config_editor/main.py", line 1882, in spawn_window
>     no_warn=no_warn)
>   File "~/rose/lib/python/rose/config_editor/main.py", line 285, in __init__
>     self.generate_menubar()
>   File "~/rose/lib/python/rose/config_editor/main.py", line 588, in generate_menubar
>     widget.connect('activate', action)
> AttributeError: 'NoneType' object has no attribute 'connect'
> ```
> 
> I think this is because the action has been renamed, but not in all places:
> 
> ```
> $ git grep 'GUI Help'
> demo/rose-config-edit/test/doc/test_suite:Help-> GUI Help
> demo/rose-config-edit/test_suite:Help-> GUI Help
> lib/python/rose/config_editor/__init__.py:TOP_MENU_HELP_GUI = "_GUI Help"
> lib/python/rose/config_editor/main.py:            ('/TopMenuBar/Help/GUI Help', self.main_handle.help),
> lib/python/rosie/browser/__init__.py:TOP_MENU_GUI_HELP = "_GUI Help"
> lib/python/rosie/browser/main.py:                     ('/TopMenuBar/Help/GUI Help',
> lib/python/rosie/browser/util.py:        <menuitem action="GUI Help"/>
> lib/python/rosie/browser/util.py:                      ('GUI Help', gtk.STOCK_HELP,
> ```
> 
> How about renaming to "Documentation"? to avoid conflict with the existing `Help` action?

Hi @oliver-sanders, thanks a lot for that. 

I've changed all the occurrences of `GUI Help` to `Documentation` so hopefully that fixes that!?

2020-10-01 09:40 UTC, oliver-sanders commented
Great, thanks!

2020-10-01 09:40 UTC, oliver-sanders approved these changes

2020-10-01 09:40 UTC, merged