mypy: fix config
metomi/rose pull request #2472
Opened 2021-07-12 15:04 UTC by oliver-sanders

Copy cylc config into rose.

2021-07-13 09:49 UTC, MetRonnie requested changes
It needs `types-aiofiles` in the `setup.py` dependencies or `mypy --install-types` twice in the GH Actions workflow. We went for the former in cylc-flow

2021-07-13 18:04 UTC, MetRonnie approved these changes
Leaving it to you to merge in case you want to add `allow_redefinition = True` as I've proposed in cylc-flow: https://github.com/cylc/cylc-flow/pull/4304

2021-07-14 08:38 UTC, oliver-sanders commented on mypy.ini
> +explicit_package_bases = True
```suggestion
explicit_package_bases = True
allow_redefinition = True
```

2021-07-14 08:38 UTC, oliver-sanders commented
Added

2021-07-14 10:36 UTC, MetRonnie approved these changes

2021-07-14 14:23 UTC, wxtim approved these changes

2021-07-14 14:24 UTC, merged